version: "2"
services:
  mjolnir:
    image: registry2.lagoni.co.uk/lagoni-engineering/mjolnir:dev
    tty: true
    stdin_open: true
    container_name: mjolnir
    build:
      dockerfile: Dockerfile
      context: "./"
    volumes:
      - src:/build/src
      - ./out:/build/out
    entrypoint: ["/build.sh"]
volumes:
  src:
