# SPDX-FileCopyrightText: 2021 Belcan Advanced Solutions
# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: Apache-2.0
header:
  site: example
  comment: example secondary config
secondary:
  modules:
    - kvm
    - kvm-intel
  networking:
    networks:
      - device: eth0
        type: ""
        dhcp: true
        ipv6: false
        addresses: []
        default-gateway: ""

      - device: eth1
        type: ""
        dhcp: false
        ipv6: false
        addresses:
          - 192.168.0.195/24
        default-gateway: ""

      - device: wg0
        type: wireguard
        dhcp: false
        ipv6: false
        addresses:
          - 10.200.4.99/32
        default-gateway: ""

    routes:
      - address: 10.200.4.0/24
        device: wg0

    nameservers:
      - 1.1.1.1
      - 8.8.8.8

  wireguard:
    - device: wg0
      listen-port: 51820
      peers:
        - public-key: vezQ++zg/pvTjZ73XAXHtTnYi618BvllGHQ37a74tgc=
          endpoint: concentrator.fouwels.app:51820
          allowed-ips:
            - 10.200.4.0/24
          persistent-keepalive: 5

  time:
    ntp: true
    hwclock: true
    servers:
      - 0.uk.pool.ntp.org
      - 1.uk.pool.ntp.org

  authenticators:
    root: 
      mode: password
      value: JDJhJDEwJGNZQUdyMWRCb1hLcXFuL0tlMmVXbi5la3V1TlFLTkRvcWJ2SGVyUVVJRDlvMFhqckN0SC5p