kvm-kernel:
	./deploy.sh kvm-kernel ./base.img ../../out/BOOTx64.EFI ./secondary.json
kvm-vnc:
	./deploy.sh kvm-vnc ./base.img ../../out/BOOTx64.EFI ./secondary.json
kvm-gtk:
	./deploy.sh kvm-gtk ./base.img ../../out/BOOTx64.EFI ./secondary.json