
deploy: deploy-kvm

deploy-emulate:
	./deploy.sh emulate ./base.img ../../out/BOOTx64.EFI ./secondary.json
deploy-emulate-headless:
	./deploy.sh emulate-headless ./base.img ../../out/BOOTx64.EFI ./secondary.json
deploy-kvm:
	./deploy.sh kvm ./base.img ../../out/BOOTx64.EFI ./secondary.json
deploy-kvm-headless:
	./deploy.sh kvm-headless ./base.img ../../out/BOOTx64.EFI ./secondary.json
