# SPDX-FileCopyrightText: 2020 Lagoni Engineering
# SPDX-FileCopyrightText: 2021 Belcan Advanced Solutions
#
# SPDX-License-Identifier: Apache-2.0

general:
  bestPracticeViolations:
    - CIS-DI-0005 # Does not apply (INFO)
    - CIS-DI-0006 # Does not apply (INFO)
    - DKL-LI-0003 # Does not apply (INFO)
