# SPDX-FileCopyrightText: 2021 Belcan Advanced Solutions
# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: Apache-2.0

header:
  site: default
  comment: default secondary configuration copied to the filesystem during auto-provisioning
secondary:
  modules: 
    - kvm
    - kvm-intel
  networking:
    networks:
      - device: eth0
        type: ""
        dhcp: true
        ipv6: false
        addresses: []
        default-gateway: ""
    routes: []
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
  wireguard: []
  time:
    ntp: true
    hwclock: false
    servers:
      - 0.uk.pool.ntp.org
      - 1.uk.pool.ntp.org
  authenticators:
    root: JDJhJDEwJGNZQUdyMWRCb1hLcXFuL0tlMmVXbi5la3V1TlFLTkRvcWJ2SGVyUVVJRDlvMFhqckN0SC5p