name: Scheduled
on:
  schedule:
    - cron:  '* */6 * * *'
env:
  REPO: ${{github.repository}}
  REGISTRY: registry2.lagoni.co.uk
  GOSEC_VERSION: 2.5.0
  ARCH: linux_amd64
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    name: Build and Scan (CVE)
    steps:
      - name: Get vars
        id: vars
        run: echo ::set-output name=TAG::${GITHUB_REF##*/}

      - name: Print headers
        run: echo "Running for target ${{env.REGISTRY}}/${{env.REPO}}:${{steps.vars.outputs.TAG}}"

      - name: Checkout repo
        uses: actions/checkout@master
        with:
          lfs: true

      - name: Docker build
        run: docker build -t ${{env.REGISTRY}}/${{env.REPO}}:${{steps.vars.outputs.TAG}} .

      - name: Run container scan
        uses: azure/container-scan@v0
        with:
          image-name: ${{env.REGISTRY}}/${{env.REPO}}:${{steps.vars.outputs.TAG}}
          severity-threshold: LOW
